version: '3.8'

services:
  discord-bot:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/angry-bot-discord:latest
    build: .
    container_name: angry-bot-discord
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=data/sqlite.db
